#!/bin/bash
set -e
set -o pipefail

# install dependencies
if [ ! -f node_modules/.bin/idl2ts ]; then
  yarn --offline || yarn || npm i
fi

# code generation
cd idl
if [ "$LANG" == "java" ]; then
  find -name '*.idl' | xargs -I {} idlj "{}"
else
  find -name '*.idl' | xargs -I {} ../node_modules/.bin/idl2ts "{}"
fi
cd ../

# move generate code
rm -rf src
mkdir src
## create directory
find idl -type f -not -name '*.idl' -exec dirname "{}" \; \
  | uniq \
  | sed 's/idl/src/' \
  | xargs mkdir -p
## move file
find idl -type f -not -name '*.idl' -exec echo "mv '{}' '{}'" \; \
  | sed 's/idl/_i_d_l_/' \
  | sed 's/idl/src/' \
  | sed 's/_i_d_l_/idl/' \
  | bash
## clean directory
find idl -type d -empty -delete

# hot fix for bug in idl2ts
mv src/client/client.ts src/demo/client.ts
mv src/server/server.ts src/demo/server.ts
mv src/smartcontract/smartcontract.ts src/demo/smartcontract.ts
find src -empty -delete

rm -rf dist
echo "all done."
