#!/bin/bash
set -e
set -o pipefail

# install dependencies
if [ ! -f node_modules/.bin/idl2ts ]; then
  yarn --offline || yarn || npm i
fi

# code generation
cd idl
if [ "$LANG" == "java" ]; then
  find -name '*.idl' | xargs -I {} idlj "{}"
else
  find -name '*.idl' | xargs -I {} ../node_modules/.bin/idl2ts "{}"
fi
cd ../

# move generate code
rm -rf src
mkdir src
## create directory
find idl -type f -not -name '*.idl' -exec dirname "{}" \; \
  | uniq \
  | sed 's/idl/src/' \
  | xargs mkdir -p
## move file
find idl -type f -not -name '*.idl' -exec echo "mv '{}' '{}'" \; \
  | sed 's/idl/_i_d_l_/' \
  | sed 's/idl/src/' \
  | sed 's/_i_d_l_/idl/' \
  | bash
## clean directory
find idl -type d -empty -delete

# hot fix for bug in idl2ts
cd src
set -x
app=$(find -empty -type f -exec dirname {} \; | uniq | sed 's,\./,,')
function fix {
  set -x
  app="$1"
  dest="$2"
  filename=$(basename "$dest" | sed 's/\.ts$//')
  src=$(echo "$dest" | sed "s/$app/$filename/")
  mv "$src" "$dest"
}
export -f fix
find -empty | xargs -I "{}" bash -c "fix "${app}" '{}'"
find -empty -delete
cd ..

# format ts code
npm run format || true
echo "remember to insert the import lines"

rm -rf dist
echo "all done."
